server:
  port: '8080'
  error:
    include-message: always
spring:
  application:
    name: MyCinema
  datasource:
    username: ${DB_USER}
    url: ${DB_DATABASE}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  config:
    import: env.properties

logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  signerKey: ${SECRET_KEY_SIGNER}
  validDuration: ${VALID_DURATION}